### ISSUE TITLE
Desktop Notifications are not working

### ISSUE THREAD

**Issue by rickinbsb** [adlerluiz/ytmdesktop#1]
**Platform**: Windows
**Version**: 1.0.0
**Description**: Desktop notifications are not working as intented
**Expected Behavior**: The app should trigger a desktop notification with name and author of the song when it starts playing
**Experienced Behavior**: No notifications
**Steps to recreate**: Play a song

**Comment by adlerluiz** [comment]
This bug happened because I changed the assets and the icon for notification was in the previous one.

Has been fixed and will be in the next release, Thank You!
