### ISSUE TITLE
v2: Grayed Out Window Caused by Region-Specific Redirect

### ISSUE THREAD

**Issue by ElectricalBoy** [adlerluiz/ytmdesktop#1168]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://github.com/ytmdesktop/ytmdesktop/assets/15651807/c9046ff8-12a3-4743-bfbd-e66723ae8ecd)

YTMD shows no useful information but a gray window. A separate browser window (Chrome in my case) opens up.
The home button (the one on the left of the settings button) is also unresponsive.

### Expected Behavior

YTMD shows something more productive than a gray window (something more related to YTM, perhaps).

### Steps To Reproduce

1. Download and install YTMD v2
2. Let the installer do its installing thing.
3. Observe YTMD with the current behavior as described above.

### YTMDesktop

v2 (2ae08e2)

### OS

Windows 11 22H2 (build 22621.2283) / Ubuntu 22.04.3 LTS

### Arch

x64

### Installation way

Manual build of the installer

### Cause

https://github.com/ytmdesktop/ytmdesktop/issues/1168#issuecomment-1732454078

### Anything else?

The first mention of this issue that I could locate was https://github.com/ytmdesktop/ytmdesktop/issues/1139#issuecomment-1728684902 - and I think that this should be tracked more as a separate issue than a comment under the v2 announcement (#1139).

**Comment by NovusTheory** [comment]
I cannot easily reproduce this problem (the latest commit adds a timeout message to reload the view). Are you able to share any log files? We're still working out adding logging to everything so it may not contain anything and some deeper digging will need to be done. Be careful when sharing log files as they may contain possibly sensitive information. On Windows the log files are located in %appdata%\YouTube Music Desktop App\logs.

**Comment by NovusTheory** [comment]
Can you show what `lastUrl` is set to in the config file? config.json in %appdata%\YouTube Music Desktop App

I'm suspecting YouTube might be redirecting as there's a log file that states it failed to load https://www.youtube.com/premium though we should've blocked that navigation and opened it in browser as it isn't in the allowed list.

**Comment by NovusTheory** [comment]
I don't think those logs are necessary. I believe the issue is to do with YTM either redirecting (for what reason I'm not sure) or it's failing to load properly. Unfortunately there is no logging for this case I believe.

Given you state your version is the latest commit I imagine you have a dev environment setup. If you can turn `enableDevTools` on in your config it will automatically launch inspect element for every window and the ytm view when you run `yarn start`. I'd like to see if the ytm view has any console logs that may not have been caught and if the url is not `music.youtube.com`

**Comment by NovusTheory** [comment]
As long as you have `enableDevTools` set to true in your config.json some windows should pop up with `yarn start` automatically. I'm looking for one that doesn't say `main_window` in the title but instead would be `youtube.com` or something similar. It should be an inspect element window (like one in the browser).

I'd like to see what the title is (should contain the url the YTM view is at) and the console to see if any logs are there that may be useful

**Comment by Alipoodle** [comment]
> ![image](https://user-images.githubusercontent.com/15651807/270089194-088c230c-fedd-4f95-a91c-87cc99144078.png)
> 
> Is this the window that you are looking for?

That's that window! However there should be 2 which show up.
One with the title `http://localhost:____/main_window` and one with YouTube Music's `https://music.youtube.com` (although given the discussion it maybe be YouTube or something else)

**Comment by NovusTheory** [comment]
Yeah that's what I noticed in the log and stated it would open in browser since it's not on the allowed list. Does opening YouTube music in your browser go to the premium page? I wonder if it's regional based or some other thing YouTube is doing

**Comment by Alipoodle** [comment]
Aha, this was something I had queried inside of our internal chat 😝

We fixed a bug for European users like myself, where YouTube redirects to concent.youtube.com for permission for cookies.

This should be a easy way to get done, depending on how we implement this. (Add this premium page to our allow list OR add a bit more or a specialized check for start up)

**Comment by NovusTheory** [comment]
Let me know if everything is working for you now with the latest commit build

**Comment by NovusTheory** [comment]
> Something doesn't quite work nicely with 2FA.

When I implemented this fix I added an allow list to redirects. Your authentication flow might be using a different url than one I've observed (possibly regional based domain). I've pushed a commit to add logging to blocked navigations & redirects so once the CI builds that it would be great if you can share the log files when you login then so I can see what is being blocked.

**Comment by NovusTheory** [comment]
Thanks, I'll look into this situation as I'm sure there are a lot more domains out there

**Comment by NovusTheory** [comment]
https://github.com/ytmdesktop/ytmdesktop/commit/d9a39f16e92d6bf9adb32bdcdf821970736fabb6

This commit should fix all the problems. Hope everything works as it should now

**Comment by Alipoodle** [comment]
Does it say anything like "you need to be a premium member"? 😅
Would be helpful to make sure that it at least informs the user of the problem in some way, however this may be a lower priority job to get sorted.

**Comment by NovusTheory** [comment]
I'll consider this problem resolved as it does the job and non-premium having issues is a low priority as they aren't able to use the application in the first place and I would like to be inclined this app isn't something that someone would flock to for a first time use of YTM so they'll likely have premium already at that point if their region requires it
