### ISSUE TITLE
Feature Request: Ad Blocker?

### ISSUE THREAD

**Issue by Dream-cake** [adlerluiz/ytmdesktop#12]
This is an good idea because the stupid YT ads

**Comment by MaxymVlasov** [comment]
Also, you can buy [YouTube Premium](https://www.youtube.com/premium) or [Music Premium](https://www.youtube.com/musicpremium)

**Comment by adlerluiz** [comment]
We do not encourage the use of adblock, even because it is the company's revenue for those who use the free version.

As @MaxymVlasov said you can buy YouTube Premium or Music Premium.
