### ISSUE TITLE
Setup executable flagged as virus

### ISSUE THREAD

**Issue by thekingziga** [adlerluiz/ytmdesktop#1358]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

So I have eset as my antivirus and when I install the app it says virus found, file update.exe and of course after restart pc, app is deleted. I also ran virus total and I dont know why it says as trojan virus.

### Expected Behavior

it shoud not trigger antivirus

### Steps To Reproduce

have eset installed
install the app

### YTMDesktop

2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

YouTube.Music.Desktop.App-2.0.5.Setup.exe

### Anything else?

![image](https://github.com/ytmdesktop/ytmdesktop/assets/58668544/9afcd261-4d2f-45f8-9ecf-483efd183b32)

**Comment by NovusTheory** [comment]
### DO NOT take my word for anything said here. Please make your own judgement decision even though I'm a maintainer.

This is a false positive from a singular vendor on VirusTotal that's likely very aggressive. Your antivirus as such is likely also being aggressive. Many applications depending what they do get flagged by specific aggressive vendors for various reasons. There is "nothing" we can do to really correct them.

For further context for others reading this issue [here's the VirusTotal link for the file in question](https://www.virustotal.com/gui/file/c1f4b5826d8c234dea07581307ff78b589f5358a1169bb28afe879bb038fadb2).
