### ISSUE TITLE
Edit Song/Album Metadata

### ISSUE THREAD

**Issue by jackstraw66** [adlerluiz/ytmdesktop#1367]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would like to edit the metadata for songs for an entire album.  After uploading albums of songs for an artist, I noticed slight differences in the metadata which caused duplicated Artists to be created.

### Solution

I would like the ability to correct metadata so albums for an artist could be correctly located together.  Ideally, this feature would be included in the "Album View" where I can see all of the songs and play them in the listed order.

### Alternatives

I could edit the metadata for the songs/albums _before_ I upload them, but many of these songs/albums are _already_ uploaded, many were migrated from the previous "Google Play" app.  After songs have been uploaded, I have not found where I could update the metadata.

**Comment by Alipoodle** [comment]
This is sadly a feature which YTM would have to integrate themselves.
