### ISSUE TITLE
"Show notification on song change" does not affect anything on Win11 23H2

### ISSUE THREAD

**Issue by ghost** [adlerluiz/ytmdesktop#1376]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I was trying to make that notification work but there is nothing happening on a song-change.

### Expected Behavior

There should be a notification.

### Steps To Reproduce

1. Install on Win11 23H2
2. Activate notification
3. Let a song end

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

YouTube.Music.Desktop.App-2.0.5.Setup.exe

**Comment by Alipoodle** [comment]
This sounds like an Upstream error if so 🤔
Will test tomorrow as I know my Work laptop is on 23H2

**Comment by Alipoodle** [comment]
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/e173c9d2-49b5-4405-9c38-823e0df9a14e)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/4a6af2b0-cc86-4268-afac-3f73cfba9b11)

I feel like there's something else like Windows is blocking the notifications for YTMD or something now?

**Comment by ghost** [comment]
Yeah it was a Windows-Setting - sorry for that!
