### ISSUE TITLE
api/v1 not working

### ISSUE THREAD

**Issue by CarlosLabrado** [adlerluiz/ytmdesktop#1379]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I am using windows 11, and I am trying to create an integration with the companion server.

I am able to get the token from the server and register my companion app, but any request after that is UNAUTHORIZED.

A simple:
`http://localhost:9863/api/v1/state`

   ![image](https://github.com/ytmdesktop/ytmdesktop/assets/4044758/aa4088f1-0c3b-4ad1-965c-14042b5c2618)

Screenshot from the companion server settings:

   ![image](https://github.com/ytmdesktop/ytmdesktop/assets/4044758/558b7d66-7889-41d2-a061-d45e0ee20086)

### Expected Behavior

I should be able to use the API with the token generated from the authentication.

### Steps To Reproduce

1. Go to settings and enable the companion authorization
2. Follow the workflow with the API HTTP POST `requestcode` then `request`
3. Do an HTTP GET for /state
4. Get a 401 unauthorized

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by NovusTheory** [comment]
The authorization header doesn't use a prefix. Just pass the token and it will work

**Comment by CarlosLabrado** [comment]
Got it. 
Something like this for anyone else wondering:
```python
url = "http://localhost:9863/api/v1/state"

payload = {}
headers = {
  'Authorization': 'your_token' # No "bearer your_token"
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
```

Thank you.
