### ISSUE TITLE
Full screen mode streches to 16:9

### ISSUE THREAD

**Issue by ooofers1** [adlerluiz/ytmdesktop#1381]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

have the album art not be stretched out and have black bars. just something more sleek and minimalist of a player to put on a secondary screen.

**Comment by NovusTheory** [comment]
This sounds like something that can be resolved with Custom CSS

**Comment by Alipoodle** [comment]
Closing as a user preference which can be achieved via the Custom CSS.
