### ISSUE TITLE
Google account sign out on app close

### ISSUE THREAD

**Issue by JHowe2905** [adlerluiz/ytmdesktop#1384]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Every time I close YTMD it seems to sign me out of my google account.

### Expected Behavior

I've had YTMD installed previously on windows 10/11 and it kept me consistently logged in. Since factory resetting my PC and redownloading, I now get signed out every time I close the app

### Steps To Reproduce

1. Open app and sign in
2. Close app
3. Open again, needs sign in

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by NovusTheory** [comment]
This sounds like the cookie encryption isn't working. I imagine many integrations within the apps settings would be saying safeStorage is unavailable?

**Comment by JHowe2905** [comment]
looking at the logs these two lines recur

[2024-06-25 22:38:33.084][renderer][error] requestStorageAccessFor: Permission denied.
[2024-06-25 22:38:33.501][renderer][info] Third-party cookie will be blocked. Learn more in the Issues tab.

**Comment by NovusTheory** [comment]
Those 2 logs are not relevant. One of them is being silenced in the next app update

**Comment by JHowe2905** [comment]
a reinstall fixed the issue
