### ISSUE TITLE
Flatpak: Pinning to Task Manager in KDE Plasma doesn't combine launched instance with pinned icon

### ISSUE THREAD

**Issue by rivalary** [adlerluiz/ytmdesktop#1385]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Launching app using the pinned icon of the flatpak version of app to Icons-Only Task Manager in KDE Plasma 6.0.5 causes a new instance of the app to appear at the end of the task manager instead of combining with the pinned icon.

### Expected Behavior

Both the pinned icon as well as the launched instance should be combined into the pinned icon.

### Steps To Reproduce

1. Install ytmdesktop Flatpak
2. Open Application Launcher, find the Ytmdesktop app, right-click and choose Pin To Task Manager
3. Open YTMDesktop by clicking on the pinned icon in the Task Manager
4. There are now two YTMDesktop icons in the task manager; one pinned and not active and the active instance of the app

### YTMDesktop

v1.13.0

### OS

Nobara Linux KDE

### OS Version

39

### Arch

x64

### Installation way

Flatpak

### Anything else?

Adding the following to the .desktop file fixes the issue:
StartupWMClass=youtube-music-desktop-app

**Comment by Alipoodle** [comment]
The version provided is v1.13 which is no longer being supported and we recommend upgrading to v2.

I'm aware there is currently no a Flatpak version for v2, but there are still other Linux versions avalaible to install, and a community member has started putting work into getting Flatpak version working.

**Comment by tfofurn** [comment]
Hello!  I am experiencing the same user as the original reporter, but with YTMDesktop v2.0.5 installed as a Flatpak on Fedora Kinoite 41.  From searching around, the issue may be that `package.json` is setting the application name to `"youtube-music-desktop-app"` but not providing the same value for `StartupWMClass` in the `.desktop` file.  The primary example I've found for instructing package.json to set StartupWMClass in the .desktop file is https://github.com/electron-userland/electron-builder/issues/4974#issuecomment-631072452.
