### ISSUE TITLE
Play on YT Music option is missing in discord rpc

### ISSUE THREAD

**Issue by harsh251004** [adlerluiz/ytmdesktop#1390]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://github.com/ytmdesktop/ytmdesktop/assets/146340558/1037cca4-82d7-441a-a8fb-f9af6d56c138)
as you can see play on yt music is missing

### Expected Behavior

play on yt music is missing

### Steps To Reproduce

play any song see in discord play in ytmdesktop option is missing

### YTMDesktop

v2.05

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by NovusTheory** [comment]
Discord updated their UI to hide the buttons on the currently logged in account's profile. Viewing it from another account shows the buttons as it normally would.

Whether this change is intentional or not is an upstream problem with Discord and not this app.

**Comment by harsh251004** [comment]
also can you change the playing YouTube music to Listening to YouTube Music
![image](https://github.com/ytmdesktop/ytmdesktop/assets/146340558/4be39c01-d4c1-469d-a8a3-77b4c96eef8e)
something like this

**Comment by NovusTheory** [comment]
> also can you change the playing YouTube music to Listening to YouTube Music

We already send a listening activity type. Another upstream related Discord issue.

**Comment by Alipoodle** [comment]
We already send the Listening status, but the discord client specifically ignores it.

This is a request a number of people have already suggested and we do as much as we can to achieve this but discord rejects it
