### ISSUE TITLE
Message data can be null, or the data inside can not be a string

### ISSUE THREAD

**Issue by Akiisqt** [adlerluiz/ytmdesktop#1394]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Electron is causing errors with the error handler

### Expected Behavior

error handler handles errors correctly

### Steps To Reproduce

I just used it

### YTMDesktop

Development

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

Fix is to just add type checking:
main -> index.js 

```ts
log.hooks.push((message, transport) => {
  if (transport !== log.transports.file) return message;

  const isSpamMessage = (data: any) => {
    return typeof data === 'string' && data.includes("Third-party cookie will be blocked.");
  };

  if (message?.data?.[0] && isSpamMessage(message.data[0])) {
    return false;
  }

  if (Array.isArray(message.data)) {
    message.data = message.data.map(data => {
      if (typeof data === 'string') {
        return data.replaceAll(/(?<=((https|http):\/\/)?.{1,64}(\..{1,64})?\..{1,64}\/)([\S]+)/gm, "[REDACTED]");
      }
      return data;
    });
  }

  return message;
});
```

**Comment by Akiisqt** [comment]
p.s. I would love to get in contact see if you'd be down to involve me in the project!

**Comment by NovusTheory** [comment]
> p.s. I would love to get in contact see if you'd be down to involve me in the project!

If you'd like to open a pull request for this then it'd be greatly appreciated.

**Comment by Akiisqt** [comment]
https://github.com/ytmdesktop/ytmdesktop/pull/1398
