### ISSUE TITLE
Discord RPC buttons do not show

### ISSUE THREAD

**Issue by Akiisqt** [adlerluiz/ytmdesktop#1396]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Buttons for the Discord RPC do not show

### Expected Behavior

Buttons for the Discord RPC do show

### Steps To Reproduce

Use the app

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Akiisqt** [comment]
Just tested again now its working?

**Comment by NovusTheory** [comment]
This would've been a duplicate of #1390. Discord has not changed this behavior
