### ISSUE TITLE
Could be added a shorter way to set the app to run with the os¿? like steam does, starting with the os

### ISSUE THREAD

**Issue by mmorales99** [adlerluiz/ytmdesktop#14]

**Comment by mingjun97** [comment]
If you are a windows user, you could add a shortcut to startup folder. See [this](https://www.thewindowsclub.com/startup-folder-in-windows-8).

Anyway, I's a good idea to integrate this feature at our application.

**Comment by mmorales99** [comment]
Well in my case, my grand mother is using it and that was the first thing she said, so just saying

**Comment by mingjun97** [comment]
Yeah, you are right. Let's make it grandmother acceptable. :)

**Comment by Venipa** [comment]
Has been added in 9bb0751d76b4cae38a717bd95a26c04a91b0682d
