### ISSUE TITLE
<The player stop every minute>

### ISSUE THREAD

**Issue by Brenokardoso** [adlerluiz/ytmdesktop#1401]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Este palyer so fica parando,já intalei umas 5 vezes

### Expected Behavior

uma fixture para limpar a memoria residual do app seria bacana

### Steps To Reproduce

1-play the music - see the error player loader

### YTMDesktop

1.13.0

### OS

pop-os

### OS Version

22.04

### Arch

ARM64

### Installation way

cli

### Anything else?

n tenho

**Comment by Akiisqt** [comment]
Current Behavior
This player just keeps stopping, I've already installed it about 5 times
Expected Behavior
a fixture to clear the app's residual memory would be cool
Anything else?
do not have

**Comment by Alipoodle** [comment]
Currently I see: ARM version of v1.13 which is not an official build we have made/supported.

Otherwise sadly this is version v1 which is not longer supported by us.
I highly recommend upgrading to v2 which is maintained and has a native Linux ARM version.
