### ISSUE TITLE
Featuring is missing from the title (Discord Rich Presence)

### ISSUE THREAD

**Issue by Sebasee009** [adlerluiz/ytmdesktop#1403]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The title is still missing featuring on Discord Rich Presence support
![Screenshot YTMDA DRP](https://github.com/user-attachments/assets/6331e5c3-9d9a-4524-abf6-47c7db42a33b)
![Screenshot YTMDA](https://github.com/user-attachments/assets/fd911704-6a39-4619-9ec8-ecda8d00cef5)

### Expected Behavior

The title shows featuring on Discord Rich Presence, would be great.

### Steps To Reproduce

1. Search Song with featuring
2. Play this song with featuring
3. See in Discord

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by NovusTheory** [comment]
Fixed by https://github.com/ytmdesktop/ytmdesktop/commit/6decd11d25e88d1088dc6d7a8c42b0ddeeef3342

The next update will include this commit and resolve this issue
