### ISSUE TITLE
companion-server likeStatus actually doesn't reflect the status

### ISSUE THREAD

**Issue by levindecaro** [adlerluiz/ytmdesktop#1409]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

while getting the .video.likeStatus json output from /api/v1/realtime nor rest api, the value is always return -1, when you hit like or dislike, the return value change to 2 or 1 respectively, however when you stop the player and replay again, it return -1 again. It is behave differently when compare with v1.13

### Expected Behavior

Return a static value for each likeStatus.

### Steps To Reproduce

1. Have the companion server enabled with valid auth token
2. play a song
3. ` curl curl -s  -H 'authorization:<token>' http://localhost:9863/api/v1/state |  jq .video.likeStatus`

### YTMDesktop

2.0.5

### OS

Mac

### OS Version

13.5

### Arch

ARM64

### Installation way

dmg

**Comment by NovusTheory** [comment]
This is fixed by https://github.com/ytmdesktop/ytmdesktop/commit/983d53a3df9648ff8899d4ad54fae8889f25c902 already which will come in a later update

**Comment by levindecaro** [comment]
@NovusTheory Thanks for pointing out that, do you have actual value mapping for unset/like/dislike?
