### ISSUE TITLE
Site downloads doesnt work

### ISSUE THREAD

**Issue by some-du6e** [adlerluiz/ytmdesktop#1412]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Title pretty self explanatory.

### Expected Behavior

I want to download it.

### Steps To Reproduce

Go to site
try to download
doesnt work

### YTMDesktop

0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

exe

### Anything else?

![](https://virus.questionable.link/6IeT8g4Ta.png)
Its not even coded in

**Comment by NovusTheory** [comment]
This is from our github pages which is not finished, we don't link to it anywhere, and is not the way we instruct users to download the app at this time.

Closing this issue because of those circumstances

You can download the app from the Releases page on GitHub
