### ISSUE TITLE
YouTube Music 3rd party app is stuck on the loading screen 

### ISSUE THREAD

**Issue by Broxy0** [adlerluiz/ytmdesktop#1418]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I open the app it gets stuck on the loading screen and won't load into YouTube Music at all.
![image_2024-08-14_235142510](https://github.com/user-attachments/assets/13f67ba2-fa05-400d-84ab-f1216cb5b1b9)

### Expected Behavior

To load into youtube music so I could use it to listen to music

### Steps To Reproduce

Open app
Wait for loading screen 
Then for me it doesn't load

### YTMDesktop

v2.0.0-rc.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Broxy0** [comment]
Ok, I was watching a tutorial that used an older version of the app. So please ignore this issue form lol..

**Comment by A-Matt** [comment]
> v2.0.0-rc.5

We're on v2.0.5 now (not RC5) so there's a NUMBER of changes.

If this is resolved I would recommend closing this ticket.
