### ISSUE TITLE
Failed to download the app on MacBook

### ISSUE THREAD

**Issue by gabe-zhang** [adlerluiz/ytmdesktop#1419]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Failed to download the app on MacBook. Tried both brew and binaries.

### Expected Behavior

-

### Steps To Reproduce

-

### YTMDesktop

2.0.0 for brew, 2.0.5 for binaries

### OS

Mac OS

### OS Version

Sonoma 14.6.1

### Arch

ARM64

### Installation way

brew install --cask ytmdesktop-youtube-music and download App-darwin-x64-2.0.5.zip from browser

### Anything else?

Hi developer team, I am having issues with downloading the app on my company MacBook. I tried to use the brew command and browser download, but neither worked. The error messages are shown below.

Are there any ways to work around this issue? Thanks!

--From brew [YouTube-Music-Desktop-App-darwin-arm64-2.0.0.zip]:
<img width="256" alt="Screenshot 2024-08-16 at 10 36 39" src="https://github.com/user-attachments/assets/c4524b83-8bba-4985-8737-cba32bd3bf24">

--From binary [YouTube-Music.Desktop.App-darwin-x64-2.0.5.zip]:
![Screenshot 2024-08-16 at 10 35 22](https://github.com/user-attachments/assets/c6f8f76d-7f1b-4a37-8378-80ead37fb666)

**Comment by Alipoodle** [comment]
YTM Desktop do not actively maintain the Brew library, so I don't know exactly towards this, and would recommend reviewing the app / downloading directly from GitHub (which I believe brew does do).

<details>
   <summary> Steps to fix this, use at your own knowlewdge, and risk </summary>
    to my knowledge there's either adding <code>--no-quarantine</code> to the end of the brew install which will avoid following this.
    Or manually acknowledging that this file is safe via running: <code>xattr -cr [Path to YouTube Music application here.app]</code>
</details>

**Comment by gabe-zhang** [comment]
Nice! The `xattr -cr` command worked for me. Thanks!
