### ISSUE TITLE
Add native Mac M-series support

### ISSUE THREAD

**Issue by Werameli** [adlerluiz/ytmdesktop#1430]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Apple Silicon native builds (because it don't work as excpected via translation layer)

### Solution

Add build option for apple silicon macs

### Alternatives

Using YTM Desktop via Rosetta, but app crashes unexpectedly when using it via translation layer

**Comment by Alipoodle** [comment]
We can, but Apple is the reason why we don't distribute them.

Without an Apple developer license ($100 a year) we cannot sign the application and make your MacBook happy. One of the main things which doesn't work is access to Keychain for securing your data including Cookies (keeping you signed in each time you restart the app) and Settings.

For the time being we see that the Arm build of Mac pointless to distribute if we have no issues with the x64/Intel builds.

You are able to build the Arm version of the app yourself and will see the same issues. There's ways of getting it to work with a few extra comments in command line but we're not going to recommend you do this on a random application.

**Comment by Alipoodle** [comment]
Additionally what are the crash reasons? And version of the app?

You should be able to copy the crash information and share it with us, to address them. Without that we can't exactly help you.

**Comment by Werameli** [comment]
> We can, but Apple is the reason why we don't distribute them.
> 
> Without an Apple developer license ($100 a year) we cannot sign the application and make your MacBook happy. One of the main things which doesn't work is access to Keychain for securing your data including Cookies (keeping you signed in each time you restart the app) and Settings.
> 
> For the time being we see that the Arm build of Mac pointless to distribute if we have no issues with the x64/Intel builds.
> 
> You are able to build the Arm version of the app yourself and will see the same issues. There's ways of getting it to work with a few extra comments in command line but we're not going to recommend you do this on a random application.

That's sad that apple wants a 100 bucks a year to release proper arm64 builds.

But speaking about unexpected chashes, they're gone. I reinstalled macOS due to other problem not related to YTM Desktop. And when I installer YTM Desktop again via Rosetta, it started working as expected without any crashes.

I don't know exact reason why it was crashing on an old installation, but now it's working
