### ISSUE TITLE
[V1] Search results screen is empty - Won't Fix

### ISSUE THREAD

**Issue by seanbelling** [adlerluiz/ytmdesktop#1435]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Type a search into search box
Autocomplete suggestions appear as expected
Selecting either a suggestion or pressing return appears to execute the search but the screen is just empty black

### Expected Behavior

Search results display as thhey did before

### Steps To Reproduce

1.Type a search into search box
2. Autocomplete suggestions appear as expected
3.Selecting either a suggestion or pressing return appears to execute the search but the screen is just empty black

### YTMDesktop

v1.13.0

### OS

macOS

### OS Version

14.4.1 

### Arch

ARM64

### Installation way

dmg I guess?

**Comment by Alipoodle** [comment]
While it's a shame to say, but we are not longer officially supporting the v1 version of the application anymore for a number of reasons. We've never forced people to update to v2 as we understand that we were not having every feature.

But sadly v1 of the app had a number of difficulties including:
- Being on a very old version of Electron (the main framework of the app) and difficult updating it to a newer version
  - In turn making it hard for people to sign in now
- Very strange requirements to even build the application without having lots of pre-requisite which aren't listed and can easily break from build to build randomly.
- General lack of security within the build.

V2 solves all of these issues and more, and is the recommended way forward. Sadly we will not be making any more updates to V1 anymore.
Remote Control + Miniplayer are features which are in the work for V2 at the moment with a number of new features already available. <3 We hope you can try the V2 version of the application.
