### ISSUE TITLE
Show/Hide doesn't work

### ISSUE THREAD

**Issue by Rithwik0604** [adlerluiz/ytmdesktop#1445]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I just upgraded to the latest version and the show/hide on double click of the media play/pause key doesn't work.

### Expected Behavior

Before if I double clicked the media play/pause key, the window would toggle between shown and hidden. Now nothing happens.

### Steps To Reproduce

1. I guess just try double clicking the media key 

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
This is a feature which wasn't ported into V2.

**Comment by Rithwik0604** [comment]
> This is a feature which wasn't ported into V2.

Oh. Okay thanks 👍
I'll close the issue.
