### ISSUE TITLE
Add browser extension

### ISSUE THREAD

**Issue by rizqiramadhannn** [adlerluiz/ytmdesktop#1447]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Hi! I just found a [extension](https://chromewebstore.google.com/detail/better-lyrics-lyrics-for/effdbpeggelllpfkjppbokhmmiinhlmg) that can make yt music implement realtime lyrics, is it possible to integrate it with the app? because it works well in browser. Thanks!

![image](https://github.com/user-attachments/assets/9e4a0340-4b24-4383-85a0-020e42f1d4b6)
![image](https://github.com/user-attachments/assets/9ef33a72-0230-4cbf-a317-4e37dcb5483e)

**Comment by NovusTheory** [comment]
As a whole - duplicate of #809 which is being worked on already and *may* be ready by 2.1.0 which likely will be the next update
