### ISSUE TITLE
Issues with signing back in after channel termination

### ISSUE THREAD

**Issue by bp88dev** [adlerluiz/ytmdesktop#1449]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Basically, I was just doing my normal stuff when I went back to YTMD after having it paused for a bit and saw something along the lines of "You signed out from another tab. Please sign in to continue." and my immediate reaction was "OH SHIT DID I JUST GET HACKED?" uh, no. I checked the activity on my Google account and, nothing. Sahara desert, if you will. But, now, whenever I click the "Sign In" button, it does nothing. I have relaunched the app multiple times. What gives?

Also, for the people who are,
1) Not nerdy enough to read it
2) You're not reading it because it's too long
well, the TL;DR of this entire thing is, it no worky.

### Expected Behavior

You should be able to re-sign in with the buttons.

### Steps To Reproduce

i have no f*cking idea.

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by bp88dev** [comment]
Now, while I wait for someone to reply, I'll listen to some music. Oh, right.

**Comment by bp88dev** [comment]
Welp, just figured out that the reason I got signed out was because my channel got terminated. Shit. Well, now you guys just need to figure out how to get me signed back in after the appeal goes through.

**Comment by Alipoodle** [comment]
Well that's an edge case I didn't expect.

But if worse comes to worse we can wipe the data for YTMD to forget you are signed in.

**Comment by bp88dev** [comment]
> Well that's an edge case I didn't expect.
> 
> But if worse comes to worse we can wipe the data for YTMD to forget you are signed in.

Lmao, ok. I do admit it is a little bit of a goofy edge case. I'll try that. Now I just need to know how to do it.

**Comment by Alipoodle** [comment]
`%appdata%/YouTube Music Desktop App`

**Comment by bp88dev** [comment]
Thanks!

**Comment by bp88dev** [comment]
Wait, so do I just nuke the entire folder?

**Comment by NovusTheory** [comment]
> Wait, so do I just nuke the entire folder?

If you want to just have YTM be signed out you can delete `%appdata%/YouTube Music Desktop App/Partitions/ytmview` so you don't have to lose everything related to the app which includes config and other data.

**Comment by bp88dev** [comment]
> > Wait, so do I just nuke the entire folder?
> 
> If you want to just have YTM be signed out you can delete `%appdata%/YouTube Music Desktop App/Partitions/ytmview` so you don't have to lose everything related to the app which includes config and other data.

Thanks! Also, if anybody's wondering, my channel's suspension has been revoked :D
