### ISSUE TITLE
No miniplayer in 2.0.5

### ISSUE THREAD

**Issue by ikeeki320** [adlerluiz/ytmdesktop#1450]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

No miniplayer button

### Expected Behavior

Miniplayer button

### Steps To Reproduce

Open the app main window

### YTMDesktop

2.0.5

### OS

Mac

### OS Version

13.7

### Arch

x64

### Installation way

.zip

### Anything else?

Just upgraded from 1.14.2 and the miniplayer button is no longer showing up.

**Comment by Alipoodle** [comment]
Duplicate of #1251
