### ISSUE TITLE
Add Remaining Time Display to Discord Rich Presence for YouTube Music

### ISSUE THREAD

**Issue by mrharryhd** [adlerluiz/ytmdesktop#1451]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would like to propose an enhancement to the Discord Rich Presence feature in YTMDesktop. The idea is to add a display of the remaining time for the currently playing song, similar to how Spotify's Rich Presence integration works.

### Solution

The feature would involve:
1. Fetching real-time playback data from YTMDesktop, including current song progress and total duration.
2. Using the Discord RPC library to update Discord status dynamically, to include details like the song title, artist, and remaining play time.
3. Setting up a system that updates this information every few seconds to ensure accuracy.

This would enhance the app's integration with Discord by providing more engaging and useful information to users, making music sharing a more interactive experience.

### Alternatives

An alternative could be to display the elapsed time instead of the remaining time, but this would be less useful for users who want to know at a glance how much longer a song will play.

### Anything else?

This enhancement aligns with features offered by other music services like Spotify and could significantly improve user engagement on platforms where YTMDesktop is used in conjunction with Discord.

**Comment by Alipoodle** [comment]
https://github.com/ytmdesktop/ytmdesktop/commit/f1cb79ae9cfdcf3abbc162f2a4472f55348aa458
This has already been implemented in the development build with this commit.

Please stay tuned for the next build where this will be added
