### ISSUE TITLE
Better Lyrics

### ISSUE THREAD

**Issue by jhoOrdann** [adlerluiz/ytmdesktop#1464]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Make the "Lyrics" tab on Youtube Music Desktop better and synchronized with the music like on mobile, I don't know why Google didn't do this natively :/
But it would be cool :)

**Comment by NovusTheory** [comment]
Duplicate of #809

Will be coming in a future release
