### ISSUE TITLE
Socket.IO Server does not correctly report trackstate on when pause

### ISSUE THREAD

**Issue by janbloemacher** [adlerluiz/ytmdesktop#1473]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When subscribed to the Socket.IO server to retrieve data, the transmission of data stops as soon as the YouTube Music player is stopped, which is expected behavior. However, when the player is paused, the `trackstate` does not consistently update. The server should continue sending a few state updates after pausing to ensure the playstate is accurately reported.

### Expected Behavior

The Socket.IO Server should send more state-update events when the player is paused so the the trackstate can correctly be read. 

The `trackstate` can have the following values: 
 > "trackState": -1 | 0 | 1 | 2, // -1 Unknown, 0 Paused, 1 Playing, 2 Buffering

### Steps To Reproduce

Subscribe to the socket.io server and listen for the state-update event, you'll see. 

### YTMDesktop

2.0.6

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

![Image](https://github.com/user-attachments/assets/1f65c36f-207d-41de-88b5-a9eba2a1a0e4)

**Comment by NovusTheory** [comment]
Using the latest commit in the development branch (outside of bundler change from Webpack -> Vite it's pretty much 2.0.6) I cannot reproduce that it isn't sending paused correctly every time.

Have you had the app running for a long time? Have you connected/disconnected a significant amount of times?

Also want to verify your client code isn't at fault. I used this for a basic test in node.js and it worked just fine.
```javascript
import io from "socket.io-client"
const client = io("http://127.0.0.1:9863/api/v1/realtime", {
    transports: ["websocket"],
    auth: {
      token: "REDACTED"
    }
});

client.on("state-update", (state) => {
    console.log(state.player.trackState);
})
```

**Comment by janbloemacher** [comment]
> Using the latest commit in the development branch (outside of bundler change from Webpack -> Vite it's pretty much 2.0.6) I cannot reproduce that it isn't sending paused correctly every time.
> 
> Have you had the app running for a long time? Have you connected/disconnected a significant amount of times?
> 
> Also want to verify your client code isn't at fault. I used this for a basic test in node.js and it worked just fine.
> 
> import io from "socket.io-client"
> const client = io("http://127.0.0.1:9863/api/v1/realtime", {
>     transports: ["websocket"],
>     auth: {
>       token: "REDACTED"
>     }
> });
> 
> client.on("state-update", (state) => {
>     console.log(state.player.trackState);
> })

... I'm beyond dumb and found the issue. I limited the updates on my application with a 1s delay. And now it dawned on me, that this is the issue, I'm sorry :(
