### ISSUE TITLE
Websocket wont work even if i have enabled companion server and even enabled requests from browser

### ISSUE THREAD

**Issue by misalibaytb** [adlerluiz/ytmdesktop#1481]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

it throws websocket error

### Expected Behavior

Normally create connection to ws of Youtube Music Desktop App server.

### Steps To Reproduce

idk

### YTMDesktop

2.0.6

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?
```js
const io= require('socket.io-client');

const socket = io("http://127.0.0.1:9863/api/v1/realtime", {

    auth: {
        token: "REDUCTED",
    },
    transports: ['websocket'],
});

socket.on('connect', () => {
    console.log('Connected to the server');
});


socket.on('disconnect', () => {
    console.log('Disconnected from the server');
});

socket.on('connect_error', (error) => {
    console.error('Connection error:', error);
});```

**Comment by XeroxDev** [comment]
You've to implement (token) authentication. You can see in the [documentation](https://github.com/ytmdesktop/ytmdesktop/wiki/v2-%E2%80%90-Companion-Server-API-v1#authentication) how to do it.

**Comment by XeroxDev** [comment]
Do you receive some other kind of exception or what does the websocket error exactly say?

But most importantly. Do you use the right socket io version? (v4.7.4 as example works)

You can also either use or look how I did it in my [ytmdesktop typescript library](https://github.com/XeroxDev/ytmdesktop-ts-companion), in the [socket-client.ts](https://github.com/XeroxDev/ytmdesktop-ts-companion/blob/main/src/shared/socket-client.ts) the socket connection is handled.

**Comment by misalibaytb** [comment]
I got it to work after some debbugging. But thank you for help
