### ISSUE TITLE
Cover art is not centered on 1440p monitors

### ISSUE THREAD

**Issue by bp88dev** [adlerluiz/ytmdesktop#1485]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The cover art is on the left side of the screen on a 1440p monitor

### Expected Behavior

The cover art should be centered

### Steps To Reproduce

Using a 1440p monitor, to into the YTMD app. Then, listen to a song and go into the queue mode.

### YTMDesktop

v2.0.6

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

![Image](https://github.com/user-attachments/assets/c95ed602-ad4d-4435-8871-949e1d84a629)

**Comment by Alipoodle** [comment]
This is a YTM issue at heart and not a YTM Desktop issue.

From a quick skim of trying to fix this myself, a lot of the common tricks for centralising it appear to break it and cause the album art to compress to 0 size. 😖

**Comment by bp88dev** [comment]
Well that's kinda sad. In that case, I'll just close the issue if it's a YTM issue.
