### ISSUE TITLE
Feature Request: BetterTouchTool and touchbar support

### ISSUE THREAD

**Issue by gcsomesz** [adlerluiz/ytmdesktop#15]
Hello guys!

Can'i hack a control presett for my macbook pro touchbar?
I use the bettertouchtool for the touchbar editing.

**Comment by adlerluiz** [comment]
Hi @gcsomesz thank you for using YTMDesktop, this feature was already being talked about for implementation, soon we will have touchbar support =)

**Comment by mingjun97** [comment]
Feel free to do that. :)

**Comment by gcsomesz** [comment]
Okay, i will try it! :)
