### ISSUE TITLE
Feature request: native title bar on macOS

### ISSUE THREAD

**Issue by vdmkotai** [adlerluiz/ytmdesktop#16]
First of all, thank you very much for creating this app!

Is it possible to use native title bar on macOS or at least move buttons to the left side, where they should be placed on macOS?

**Comment by mingjun97** [comment]
It now looks like this. Enjoy it. :)
![image](https://user-images.githubusercontent.com/15214491/58583926-ef24e580-8209-11e9-943c-7b37ea3efe54.png)

**Comment by vdmkotai** [comment]
Amazing, thank you so much!

**Comment by adlerluiz** [comment]
Merged to master
