### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by N1coc4colA** [adlerluiz/ytmdesktop#19]
Hello, I wanted to have ytb music on desktop. I use Linux (Deepin 15.10.1) and I installed every depedencies. I used 'npm i' (the 'npm install') and used 'npm start' in terminal. The problem is the language. I opened some html files to check (like always) to see how it'll looks like. In the browsers, you can't use the main page due to the react components. But I saw your app works properly and include the Linux OS in the list of support. I think your app, don't support the french laguage. When it open, every components are here: action buttons, title, settings, every components work properly. But I have a big 'fr_ALL' where normally there is the UI. I understood you use a component of react to put a language. Do you have a way to put your own language (add manually a translation) or force make it in english or put automatically if a translation isn't valaible in english?
If you have a way to add a translation manually, I'll give you the french  translation from english I did.

**Comment by mingjun97** [comment]
Hi N1coc4colA, you may check the folder `locales`, make a copy of `en.json` and do your translation. Then open a pull request so that we can merge your contribution to the main stream. By the way, don't forget to put corresponding options in `settings.html` at around 235 lines which looks like this

>                       <select id="select-app-language">
>                         <option value="en">English</option>
>                         <option value="pt">Português</option>
>                         <option value="zh">简体中文</option>
>                         <option value="ko">한국어</option>
>                       </select>

Thanks for your contributions.

**Comment by mingjun97** [comment]
I've checked the logic of our translation provider. I guess it provides english by default no matter what configuration you set in your environment. By the way, if you have hard time to open a pull request, you could paste your `fr.json` file here and we will do it for you. :)

**Comment by N1coc4colA** [comment]
[fr.txt](https://github.com/adlerluiz/ytmdesktop/files/3307724/fr.txt)
thanks for this quick answer!! I finished to do the translation. You just have to change the .txt into .json.
Thanks for the answer! I'll test to see if it works. Maybe it's the country settings, maybe this service isn't valaible in our country... And don't worry if some words haven't been changed, it's cause we use a lot of english words and sometimes there is no 'good' translation so we use the english.

**Comment by mingjun97** [comment]
Good job. THX.

**Comment by N1coc4colA** [comment]
;)

**Comment by mingjun97** [comment]
By the way, the language name should be `Le français` or just `French` is OK?

**Comment by N1coc4colA** [comment]
I forgot to translate 'Queue' somewhere, replace it by "Liste"

**Comment by N1coc4colA** [comment]
the first one

**Comment by mingjun97** [comment]
Got it. Thanks.

**Comment by N1coc4colA** [comment]
The translation is right, all works properly.... or not...

**Comment by N1coc4colA** [comment]
![DeepinScreenshot_20190619131253](https://user-images.githubusercontent.com/50690360/59797180-f9c81d00-9293-11e9-8d51-cb67994af4dd.png)
the error continue...

**Comment by N1coc4colA** [comment]
"YouTube Music is not available in your area" of https://music.youtube.com/

**Comment by mingjun97** [comment]
Things awkward.. 

I think you could expect the next version which support Proxy feature so that you may use VPN/Proxy server in another country to get served :)

Anyway, thanks for your contribution.

**Comment by N1coc4colA** [comment]
Now that's right, it's the country, I used a VPN to put mi IP in USA and it works well.

**Comment by N1coc4colA** [comment]
Now waiting for your Proxy feature ;)

**Comment by mingjun97** [comment]
Cool. I've pushed the translation file into the development branch. Just wait for the owner to merge it into master branch.

**Comment by adlerluiz** [comment]
There is how to automatically pick up the language you use, but since YTMDesktop is still recent and has few language options, I decided to leave it as default in English, but in the future when there are more languages we will modify it and it will pick up automatically.

Thank you for the translation @N1coc4colA
