### ISSUE TITLE
Localization to Russian

### ISSUE THREAD

**Issue by KovalevArtem** [adlerluiz/ytmdesktop#27]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by Venipa** [comment]
https://github.com/adlerluiz/ytmdesktop/tree/master/locales

**Comment by adlerluiz** [comment]
Hey @KovalevArtem, thanks for offering help!
YTMDesktop currently supports these languages:

![image](https://user-images.githubusercontent.com/2112638/60346556-c3745700-9991-11e9-8ff7-e17774a994f2.png)

I've added the project to crowdin, you can check it out and help with translating to russian:
https://crowdin.com/project/ytmdesktop
