### ISSUE TITLE
Little stupid bug with the preview in windows 10

### ISSUE THREAD

**Issue by mmorales99** [adlerluiz/ytmdesktop#28]
I'm using win10, and when i put the mouse over my toolbar it shows the preview of the app with the stop/play, next and back, and the like/dislike button that changes color when they are pressed.
Well, when i have liked a song on the web page or through the app, it dont shows correctly in this little buttons for liking, and if its liked and pressed, they dislike the song.

**Comment by adlerluiz** [comment]
Hi @mmorales99 

Thanks for using YTMDesktop, this is a know issue, that has corrected on development branch.

As soon as possible, will be available as an update.

**Comment by mmorales99** [comment]
oo noice
