### ISSUE TITLE
Default music player for Windows 10

### ISSUE THREAD

**Issue by kostiantyn-korniienko** [adlerluiz/ytmdesktop#797]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

There is no option to setup YTM as a default music player in Windows 10

**Describe the solution you'd like**

I can set YTM as the default music player for Windows 10

**Describe alternatives you've considered**

Didn't found any. You can set up other player, as default one, but not YTM.

**Additional context**

Available options:
![image](https://user-images.githubusercontent.com/37180625/130786713-e7fb7c5a-4663-4874-bb51-8e3eacdf7cd6.png)

Was able to resolve by https://github.com/ytmdesktop/ytmdesktop/issues/797#issuecomment-905454490 , but it would be good to have this working from the box.

**Comment by kostiantyn-korniienko-aurea** [comment]
was able to resolve by executing the following in `CMD`:

```
assoc .ytm=YTMPlayer
ftype YTMPlayer="C:\Users\<username>\AppData\Local\Programs\youtube-music-desktop-app\YouTube Music Desktop App.exe"
assoc .mp3=YTMPlayer
```

And only then it appears in the default list, and you can reassociate that.
First, it opened Microsoft Browser for few times, until I have opened the music player from the CMD executing 
`"C:\Users\<username>\AppData\Local\Programs\youtube-music-desktop-app\YouTube Music Desktop App.exe"`

Only then started open as expected from my media keyboard.
