### ISSUE TITLE
chromium extensions

### ISSUE THREAD

**Issue by HydraCatYT** [adlerluiz/ytmdesktop#835]
- [.] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [.] I verified that there is no open issue for the same subject.
This isn't a bug report but is it question/recomendation

**Describe the solution you'd like**
So Can You Make it easier to add chromium extensios

**Describe alternatives you've considered**
umm so I don't have time to recompile so its it ok if  can just be there

**Additional context**
none
![index](https://user-images.githubusercontent.com/68640795/136674873-fdba724d-e6c5-40f7-88b2-4ea20be6ef48.jpg)

**Comment by NovusTheory** [comment]
This is unlikely to be supported given this isn't a goal of electron itself to support and it has limited support for them in general as well as things operating differently in the API so you'd be lucky if an extension of your choice works
