### ISSUE TITLE
download with download manager 

### ISSUE THREAD

**Issue by ghost** [adlerluiz/ytmdesktop#843]
first of all . i used [ymusic ](ymusic.io) in android for a long time and that includes my basic needs  as youtube client 
u can try it for knowing more what i am talking about for now 

so, why thre is no download button 

and if u will give download music or custom download options 
please think for download manager 

and try to keep ytmdesktop lightweight as much as possible 
because as the first time i lauch it . it takes my whole bandwidth so. 
yeah make offline option too. 

is my request are accpted then that ytm is becomes my daily driver for lifetime 

actually the things i mentioned is the real key feature wich are misssing

**Comment by Alipoodle** [comment]
We are a wrapper of YouTube Music to provide some additional features to the website in a Desktop Environment.
We intended to keep within YouTube Music's ToS as much as possible, including no implementing a Native AdBlock & Downloader as this is not intended by YouTube.

If you're looking for a more Light weight YouTube Music it's probably better to use the Native Progressive Web App version of YouTube Music.
However this like us does not include:
- Downloads
- Offline mode

These will have to be implemented by YouTube Music themselves for it to be included in either versions.

**Comment by happuji** [comment]
sir that all is what u said is not what i was expecting for
😢
