### ISSUE TITLE
Make music available offline

### ISSUE THREAD

**Issue by ghost** [adlerluiz/ytmdesktop#857]
- [*] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [*] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
We can’t listen to music when offline.

**Describe the solution you'd like**
Create a “Download” button and when it’s clicked, let ytmdesktop start downloading the music (by using youtube-dl or something) which is opened.

**Describe alternatives you've considered**
Download the music using smartphone’s ytm app with ytm premium account.

**Additional context**
I saw this [post on reddit](https://www.reddit.com/r/YoutubeMusic/comments/qec2df/win11s_android_compatibility_layer_makes_this_a/?utm_source=share&utm_medium=mweb) and thought that it will be interesting if we could download songs using ytmdesktop and play it directly from ytmdesktop.

**Comment by RasitAyaz** [comment]
This would be an awesome feature, can it be made?

**Comment by Alipoodle** [comment]
No we're not YTM, and we're not in support of downloading using youtube-dl or anything.
This feature may eventually get added as YouTube has recently added support for downloading videos with Premium.

**Comment by ManneWas** [comment]
Any plans on integrating the feature seeing as it's possible for premium accounts on the phone? I do understand though if it's not possible due to any number of reasons (API limitations or other less technical google policy ones) but felt it could be worth asking again now after some time has passed.
